# Generated by Django 3.2.15 on 2022-09-11 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20220825_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderquantity',
            name='frozen_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
            preserve_default=False,
        ),
    ]
