# Generated by Django 3.2.15 on 2022-08-30 20:08

from django.db import migrations


def copy_prices(apps, schema_editor):
    # noinspection PyPep8Naming
    ProductOrderQuantity = apps.get_model('foodcartapp', 'ProductOrderQuantity')

    for ordered_product in ProductOrderQuantity.objects.all().iterator():
        ordered_product.frozen_price = ordered_product.product.price
        ordered_product.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0039_productorderquantity_frozen_price'),
    ]

    operations = [
        migrations.RunPython(copy_prices),
    ]
