# Generated by Django 3.2.15 on 2022-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20220830_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Новый'), ('A', 'Передан ресторану'), ('D', 'Передан курьеру'), ('F', 'Завершён'), ('C', 'Отменён')], db_index=True, default='N', max_length=1, verbose_name='Статус'),
        ),
    ]
