# Generated by Django 3.2.15 on 2022-09-16 18:46

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20220916_1821'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('called_at__gte', django.db.models.expressions.F('created_at')), ('called_at__isnull', True), _connector='OR'), name='call_after_create'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('delivered_at__gte', django.db.models.expressions.F('called_at')), ('called_at__isnull', True), ('delivered_at__isnull', True), _connector='OR'), name='delivered_after_call'),
        ),
    ]
