# Generated by Django 3.2.15 on 2022-10-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_selected_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Не выбран'), ('CASH', 'Наличный расчёт'), ('SITE', 'Картой на сайте'), ('CARD', 'Картой курьеру')], db_index=True, default='', max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
